name: mangadex_online
description: Demo con buscador multi-fuente (mock), guardado de fichas y biblioteca.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

flutter:
  uses-material-design: true

