name: Build Android APK (v3 folder)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Flutter doctor
        run: flutter doctor -v

      # 👇 trabaja DENTRO de tu app real
      - name: Ensure Android platform
        working-directory: mangadex_online_starter_v3
        run: flutter create . --platforms=android

      - name: Accept Android SDK licenses
        shell: bash
        run: |
          set +e
          yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          echo "✅ Licencias aceptadas (ignorando broken pipe)"


      - name: Pub get
        working-directory: mangadex_online_starter_v3
        run: flutter pub get

      - name: Build DEBUG apk (rápido)
        working-directory: mangadex_online_starter_v3
        run: flutter build apk --debug --no-tree-shake-icons

      - name: Upload DEBUG
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: mangadex_online_starter_v3/build/app/outputs/flutter-apk/app-debug.apk

      - name: Build RELEASE apk
        working-directory: mangadex_online_starter_v3
        run: flutter build apk --release --no-shrink

      - name: Upload RELEASE
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mangadex_online_starter_v3/build/app/outputs/flutter-apk/app-release.apk
